### PR TITLE
Support collecting smaller logs

### PR DESCRIPTION
**Pull request by edgarsi**

### CODE REVIEW

**Comment by Krinkle** [comment]
Hi @edgarsi,

Thanks for sharing this patch! Apologies for the late response. This repository is a mirror of <https://gerrit.wikimedia.org/g/performance/arc-lamp> (See https://www.mediawiki.org/wiki/Developer_access for how to contribute).

If I understand correctly, you'd like to lower the number of samples collected. To do this, I would recommend using the sampling interval setting instead of discarding here at the processing layer.

For HHVM/Xenon (see [1.0.0 docs](https://github.com/wikimedia/arc-lamp/tree/1.0.0#quick-start)), this can be done through the `hhvm.xenon.period` setting.

For PHP7/Excimer, (see [2019 docs](https://github.com/wikimedia/arc-lamp/blob/0b216416/ArcLamp.php#L27)), this can be done through the `excimer-period` option.

**Comment by edgarsi** [comment]
Hi @Krinkle,

We are collecting logs over multiple granularities - from minutely to monthly. `hhvm.xenon.period` is configured to be frequent enough for the smallest granularity. Storing monthly logs of that frequency, however, is unfeasible.

You do already support multiple log periods, so the necessity for this change is not unnatural or awkward.

This is how a configuration, using the feature, looks in production:
```
logs:
  - format: "%Y-%m-%d_%H_%M"
    period: minutely
    retain: 60
  - format: "%Y-%m-%d_%H"
    period: hourly
    write_every: 10
    retain: 24
  - format: "%Y-%m-%d"
    period: daily
    write_every: 100
    retain: 30
  - format: "%Y-%W"
    period: weekly
    retain: 52
    write_every: 10000
  - format: "%Y-%m"
    period: monthly
    retain: 12
    write_every: 10000
```

**Comment by Krinkle** [comment]
@edgarsi I agree :) Sorry for the delay and the mess above.

I've submitted your patch via our Gerrit Code Review at <https://gerrit.wikimedia.org/r/#/c/operations/puppet/+/606789/>.

I changed the sampling to ocurr before the `write()` call as I believe it is expected for the `all` and tags files to match up. Would that work for you?

**Comment by edgarsi** [comment]
Absolutely! Tnx for rewriting it cleaner!

**Pull request closed without merging**
